
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  socket-io-scale
  labels:
    name:  socket-io-scale
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  socket-io-scale
    spec:
      containers:
      - image:  socket-io-scale
        name:  socket-io-scale
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        env:
        - name:  REDIS_DB
          value:  redis-db-service       
        ports:
        - containerPort:  3000
          name:  socket-io-scale
        imagePullPolicy: Never
      restartPolicy: Always